### ISSUE TITLE
Legit?

### ISSUE THREAD

**Issue by Subtelny** [HaKIMus/Hank#1]
Hello,
I wanna use this for my ING Bank institution.
That code seems be legit and perfect writed.
But i typed into setMoney method, bilion $ and where is my fckn money?

There is my bank acc:
98 1160 2201 0000 0004 3725 2412

**Comment by HaKIMus** [comment]
Hi Subtelny,

we'll work on it as soon as possible!

Okay! I got it! There's a limit of money on account:

https://github.com/HaKIMus/Hank/blob/808aceedb564ed5a4d2f463bebadf41198255e9a/src/Domain/BankAccount/Balance.php#L90

Try to delete that one and everything should work correct! Oh, don't foregt about limit in twig's templates.

https://github.com/HaKIMus/Hank/blob/master/templates/panel/pay-in-client-panel.twig#L19

Here you go!

Cheers from Hank's "Team"!

:rofl:
